#!/usr/bin/env python3
"""Build or validate a canonical GSAS-II refinement report."""

from __future__ import annotations

import argparse
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from refinement_audit import (
    METRIC_LABELS,
    candidate_safety_errors,
    sha256,
    write_json_atomic,
)


MARKER_START = "<!-- BEGIN GSAS-II-METRICS schema=1 -->"
MARKER_END = "<!-- END GSAS-II-METRICS -->"


def load_summary(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("schema_version") != 1:
        raise SystemExit("candidate_summary.json schema_version must be 1")
    if not isinstance(data.get("candidates"), list):
        raise SystemExit("candidate_summary.json has no candidates list")
    return data


def selected_candidate(
    summary: dict[str, Any], requested: str | None
) -> dict[str, Any]:
    name = summary.get("selected_candidate")
    if not name:
        raise SystemExit(
            "No selected candidate. Run select_refinement_candidate.py after "
            "the dialectical review."
        )
    if requested and requested != name:
        raise SystemExit(
            f"--selected={requested} differs from summary selection {name}"
        )
    matches = [item for item in summary["candidates"] if item.get("name") == name]
    if len(matches) != 1:
        raise SystemExit(f"Selected candidate is absent or duplicated: {name}")
    candidate = matches[0]
    safety_errors = candidate_safety_errors(candidate)
    if safety_errors:
        raise SystemExit(
            "Selected candidate failed the automatic safety gate: "
            + "; ".join(safety_errors)
        )
    return candidate


def metric_text(item: dict[str, Any] | None, decimals: int = 4) -> str:
    if not item or item.get("value") is None:
        return "not available"
    return f"{float(item['value']):.{decimals}f}%"


def build_marker(
    summary_path: Path, candidate: dict[str, Any]
) -> dict[str, Any]:
    return {
        "schema_version": 1,
        "candidate_summary_sha256": sha256(summary_path),
        "selected_candidate": candidate["name"],
        "metrics": {
            key: {
                "label": METRIC_LABELS[key],
                "value": candidate["metrics"][key]["value"],
                "source": candidate["metrics"][key]["source"],
            }
            for key in METRIC_LABELS
        },
        "cell": {
            key: {
                "value": item["value"],
                "esd": item["esd"],
                "formatted": item["formatted"],
            }
            for key, item in candidate["cell"].items()
        },
        "instrument": {
            key: {
                "value": item["value"],
                "esd": item["esd"],
                "formatted": item["formatted"],
                "refined": item["refined"],
            }
            for key, item in candidate["instrument"].items()
        },
    }


def candidate_verdict(item: dict[str, Any], selected_name: str) -> str:
    if item.get("status") != "succeeded":
        return "Failed"
    if item.get("name") == selected_name:
        return "Selected final"
    maximum = item.get("correlations", {}).get("max_abs_percent")
    if maximum is not None and maximum >= 95:
        return "Reject/high correlation"
    if item.get("classification") == "exploratory":
        return "Exploratory"
    return "Sensitivity candidate"


def build_report(
    summary_path: Path,
    summary: dict[str, Any],
    candidate: dict[str, Any],
) -> str:
    marker = build_marker(summary_path, candidate)
    metrics = candidate["metrics"]
    cell = candidate["cell"]
    instrument = candidate["instrument"]
    lines = [
        f"# GSAS-II Rietveld refinement report: {summary['sample_id']}",
        "",
        "## Result status",
        "",
        f"- Selected candidate: `{candidate['name']}`",
        f"- GPX: `{summary['selected_files']['gpx']['path']}`",
        f"- Real GSAS-II result: yes",
        f"- Converged: {candidate['convergence']['converged']}",
        f"- SVD0: {candidate['convergence']['SVD0']}",
        (
            "- Maximum shift/s.u.: "
            f"{candidate['convergence']['max_shift_over_su']}"
        ),
        "- Figure generated by this skill: no",
        "",
        "## Input provenance",
        "",
        "| Role | Path | SHA-256 |",
        "|---|---|---|",
    ]
    for role in ("xrd", "cif", "instrument"):
        item = summary["inputs"][role]
        lines.append(f"| {role} | `{item['path']}` | `{item['sha256']}` |")
    lines.extend(
        [
            "",
            "## Refinement sequence",
            "",
            "The instrument U/V/W profile was declared "
            f"`{summary['settings']['instrument_profile_status']}` and was "
            f"handled as `{summary['settings']['profile_mode']}`. Scale and "
            "background were refined first. Cell-only, Zero-only, simultaneous "
            "cell+Zero, cell-then-Zero, and Zero-then-cell branches were then "
            "compared before any profile release.",
            "",
            "## Authoritative residual metrics",
            "",
            "| Metric | Value | Definition | Source |",
            "|---|---:|---|---|",
        ]
    )
    for key in ("Rwp", "Rp", "R_bkg", "wR_bkg", "RF", "RF2", "GOF"):
        item = metrics[key]
        value = (
            f"{float(item['value']):.4f}%"
            if item.get("value") is not None and key != "GOF"
            else (
                f"{float(item['value']):.4f}"
                if item.get("value") is not None
                else "not available"
            )
        )
        lines.append(
            f"| {METRIC_LABELS[key]} | {value} | {item['definition']} | "
            f"{item['source']} |"
        )
    lines.extend(
        [
            "",
            "`R-bkg` and `wR-bkg` are profile residuals after background "
            "subtraction. `RF` and `RF²` are Bragg reflection metrics. They "
            "must not be reported under one ambiguous label.",
            "",
            "## Cell parameters with standard uncertainties",
            "",
            "| Parameter | value(esd) | Raw value | Raw esd |",
            "|---|---:|---:|---:|",
        ]
    )
    for key in (
        "length_a",
        "length_b",
        "length_c",
        "angle_alpha",
        "angle_beta",
        "angle_gamma",
        "volume",
    ):
        item = cell[key]
        lines.append(
            f"| {key} | {item['formatted']} | {item['value']} | "
            f"{item['esd'] if item['esd'] is not None else 'not available'} |"
        )
    lines.extend(
        [
            "",
            "## Instrument terms",
            "",
            "| Parameter | value(esd) | Refined |",
            "|---|---:|---|",
        ]
    )
    for key, item in instrument.items():
        lines.append(f"| {key} | {item['formatted']} | {item['refined']} |")
    lines.extend(
        [
            "",
            "## Geometry sensitivity and candidate review",
            "",
            "| Candidate | Parent | Rwp | Max abs correlation | Warnings | Verdict |",
            "|---|---|---:|---:|---|---|",
        ]
    )
    for item in summary["candidates"]:
        rwp = metric_text(item.get("metrics", {}).get("Rwp"))
        maximum = item.get("correlations", {}).get("max_abs_percent")
        correlation = (
            f"{maximum:.2f}%" if isinstance(maximum, (int, float)) else "n/a"
        )
        warnings = "; ".join(item.get("warnings", [])) or item.get("error", "none")
        warnings = warnings.replace("|", "/")
        lines.append(
            f"| {item.get('name')} | {item.get('parent')} | {rwp} | "
            f"{correlation} | {warnings} | "
            f"{candidate_verdict(item, candidate['name'])} |"
        )
    residual_peaks = candidate["residual_audit"]["positive_local_maxima"]
    lines.extend(
        [
            "",
            "## Positive residual-peak audit",
            "",
            "| 2theta | Obs-calc | Observed | Residual/observed |",
            "|---:|---:|---:|---:|",
        ]
    )
    for peak in residual_peaks:
        fraction = peak["fraction_of_observed_percent"]
        lines.append(
            f"| {peak['two_theta']:.4f} | {peak['obs_minus_calc']:.4f} | "
            f"{peak['observed']:.4f} | "
            f"{fraction:.2f}% |"
            if fraction is not None
            else (
                f"| {peak['two_theta']:.4f} | {peak['obs_minus_calc']:.4f} | "
                f"{peak['observed']:.4f} | n/a |"
            )
        )
    lines.extend(
        [
            "",
            "## Evidence boundary",
            "",
            "- Numerical convergence does not prove model correctness.",
            "- Do not claim site occupancy, oxygen deficiency, local structure, "
            "microstrain, crystallite size, or strict phase purity unless the "
            "selected model and independent evidence support those claims.",
            "- Treat an uncalibrated cell as an apparent value and report the "
            "cell/Zero sensitivity.",
            "- Inspect major positive residual peaks before calling the model "
            "complete.",
            "",
            "## Machine-verifiable metrics",
            "",
            MARKER_START,
            "```json",
            json.dumps(marker, ensure_ascii=False, indent=2),
            "```",
            MARKER_END,
            "",
        ]
    )
    return "\n".join(lines)


def extract_marker(text: str) -> dict[str, Any]:
    pattern = (
        re.escape(MARKER_START)
        + r"\s*```json\s*(.*?)\s*```\s*"
        + re.escape(MARKER_END)
    )
    match = re.search(pattern, text, flags=re.DOTALL)
    if not match:
        raise ValueError("machine-verifiable GSAS-II metrics block is missing")
    return json.loads(match.group(1))


def validate_report(
    report_path: Path,
    summary_path: Path,
    candidate: dict[str, Any],
) -> dict[str, Any]:
    text = report_path.read_text(encoding="utf-8")
    expected = build_marker(summary_path, candidate)
    actual = extract_marker(text)
    errors = []
    if actual != expected:
        errors.append(
            "Embedded metrics block does not exactly match candidate_summary.json"
        )
    human_text = text.split(MARKER_START, 1)[0]
    if re.search(r"\bRb\b", human_text):
        errors.append("Ambiguous label Rb found; use R-bkg or RF explicitly")
    if re.search(r"\bwRb\b", human_text):
        errors.append("Ambiguous label wRb found; use wR-bkg explicitly")
    for required in ("R-bkg", "wR-bkg", "RF", "RF²"):
        if required not in human_text:
            errors.append(f"Required metric label is missing: {required}")
    for key, item in candidate["cell"].items():
        if item["formatted"] not in human_text:
            errors.append(
                f"Formatted uncertainty for {key} is missing: {item['formatted']}"
            )
    return {
        "schema_version": 1,
        "validated_at": datetime.now(timezone.utc).isoformat(),
        "status": "pass" if not errors else "fail",
        "report": {
            "path": str(report_path),
            "bytes": report_path.stat().st_size,
            "sha256": sha256(report_path),
        },
        "candidate_summary": {
            "path": str(summary_path),
            "sha256": sha256(summary_path),
        },
        "selected_candidate": candidate["name"],
        "checks": {
            "embedded_metrics_match": actual == expected,
            "unambiguous_R_factor_labels": not any(
                "Ambiguous label" in error for error in errors
            ),
            "cell_uncertainties_present": not any(
                "Formatted uncertainty" in error for error in errors
            ),
        },
        "errors": errors,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--candidate-summary", required=True)
    parser.add_argument("--selected")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write-report")
    group.add_argument("--report")
    parser.add_argument("--validation-output", required=True)
    parser.add_argument("--replace", action="store_true")
    args = parser.parse_args()

    summary_path = Path(args.candidate_summary).expanduser().resolve()
    if not summary_path.is_file():
        raise SystemExit(f"Candidate summary not found: {summary_path}")
    summary = load_summary(summary_path)
    candidate = selected_candidate(summary, args.selected)

    if args.write_report:
        report_path = Path(args.write_report).expanduser().resolve()
        if report_path.exists() and not args.replace:
            raise SystemExit(
                f"Report exists; use --replace to regenerate: {report_path}"
            )
        report_path.parent.mkdir(parents=True, exist_ok=True)
        temporary = report_path.with_name(f".{report_path.name}.tmp")
        temporary.write_text(
            build_report(summary_path, summary, candidate), encoding="utf-8"
        )
        temporary.replace(report_path)
    else:
        report_path = Path(args.report).expanduser().resolve()
        if not report_path.is_file():
            raise SystemExit(f"Report not found: {report_path}")

    try:
        validation = validate_report(report_path, summary_path, candidate)
    except Exception as exc:
        validation = {
            "schema_version": 1,
            "validated_at": datetime.now(timezone.utc).isoformat(),
            "status": "fail",
            "report": {"path": str(report_path)},
            "candidate_summary": {"path": str(summary_path)},
            "selected_candidate": candidate["name"],
            "checks": {},
            "errors": [f"{type(exc).__name__}: {exc}"],
        }
    validation_path = Path(args.validation_output).expanduser().resolve()
    write_json_atomic(validation_path, validation)
    print(report_path)
    print(validation_path)
    if validation["status"] != "pass":
        for error in validation["errors"]:
            print(f"ERROR: {error}", file=__import__("sys").stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
